#!/bin/bash

# List of deployments to delete (all except the latest one)
deployments=(
    "https://agent-bio-summary-19rtfilh1-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-84wu0rclk-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-obdmiybz1-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-6o4bydduf-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-jllf5uvzz-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-j5vbo4lsl-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-o59tr24s0-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-5lrf0n43s-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-a111sox8d-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-i774nzrmt-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-lq5sfodwy-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-4nbouewhz-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-fitqjdukd-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-4mvcgakq5-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-1ddeuto6m-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-a8ja2ia0m-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-655om3ckc-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-m5hv0orv3-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-ft78mtcgl-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-1uu1qc2zd-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-qrrtq6z9g-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-beo6no7bq-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-d87m5j0lv-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-jtlfknlkd-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-4mii7vuv4-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-o9qp81p33-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-kfzw7if2e-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-22vs55owa-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-93l40j2ik-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-5akfoz5jr-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-2sf1r67ox-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-7p25lfdgc-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-hmd0dfvuq-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-qfb9ierty-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-j7ftwxgmt-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-etzln7g4m-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-b3yd97bw8-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-n2ke72avg-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-8rifkxgxh-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-c278bgnhi-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-in1y6kj5u-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-iwsibsrb2-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-mbytqh1qg-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-1qetfg6hf-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-3kyrgwv2s-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-brnvkp3d7-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-5zhm87dhf-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-hgibcxanj-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-6i7vg7o9z-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-mle8ovu9w-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-phd4qv8on-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-pjs9t5kby-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-dtkyashtg-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-lfzyvmeh4-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-bqyexy1vy-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-oi04k5s1n-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-4sq0xsvsx-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-71mzyr6dj-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-2aag861bw-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-izl501qk3-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-d8d8e8hak-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-op1xsuczn-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-87aupsrik-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-jxzfsmmzh-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-fdezkmke4-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-dk6r3bgt9-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-g9fo3nqcj-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-ptmsjwffz-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-69mgucw0s-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-nppvdd1y9-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-dhncbr24b-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-oyntm6ofk-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-g0kpo7z5a-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-l5gsp39zd-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-lc8i89liq-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-1ea5mkjyq-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-4yrs182p8-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-pzx976uis-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-3vqyjavlu-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-17hh6z1ns-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-fcrlmujxf-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-2vg9885zz-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-2c1jx5wch-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-6ytwvrj74-ashtekars-projects.vercel.app"
    "https://agent-bio-summary-lmjhn4nu2-ashtekars-projects.vercel.app"
)

echo "Deleting ${#deployments[@]} old deployments..."

for deployment in "${deployments[@]}"; do
    echo "Deleting: $deployment"
    vercel remove "$deployment" --yes
done

echo "Cleanup complete!"
