import { Resend } from 'resend'
import { EmailRecipient, DailySummary } from './types'
import { marked } from 'marked'

export class EmailService {
  private resend: Resend

  constructor(apiKey: string) {
    this.resend = new Resend(apiKey)
  }

  async sendDailySummary(recipients: EmailRecipient[], summary: DailySummary): Promise<boolean> {
    try {
      const emailPromises = recipients
        .filter(recipient => recipient.active || recipient.is_active)
        .map(recipient => this.sendEmailToRecipient(recipient, summary))

      const results = await Promise.allSettled(emailPromises)
      const successCount = results.filter(result => result.status === 'fulfilled').length

      console.log(`Email sent successfully to ${successCount}/${recipients.length} recipients`)
      return successCount > 0
    } catch (error) {
      console.error('Error sending daily summary emails:', error)
      return false
    }
  }

  private async sendEmailToRecipient(recipient: EmailRecipient, summary: DailySummary): Promise<void> {
    const emailHtml = this.generateEmailHTML(summary, recipient.name)
    const emailText = this.generateEmailText(summary, recipient.name)

    await this.resend.emails.send({
      from: 'AgentBioSummary <noreply@news.ashtekar.net>',
      to: recipient.email,
      subject: `Synthetic Biology Daily Digest - ${summary.date}`,
      html: emailHtml,
      text: emailText
    })
  }

  private generateEmailHTML(summary: DailySummary, recipientName: string): string {
    // Convert markdown to HTML for summaries
    const dailySummaryHtml = marked.parse(summary.dailySummary || '')
    const top10SummaryHtml = marked.parse(summary.top10Summary || '')
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Synthetic Biology Daily Digest</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; }
          .content { background: white; padding: 30px; border-radius: 10px; margin-top: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .section { margin-bottom: 30px; }
          .section h2 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
          .article { background: #f8f9fa; padding: 15px; margin: 10px 0; border-radius: 5px; border-left: 4px solid #3498db; }
          .article h3 { margin: 0 0 10px 0; color: #2c3e50; }
          .article p { margin: 5px 0; color: #666; }
          .source { font-size: 12px; color: #999; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .highlight { background: #fff3cd; padding: 15px; border-radius: 5px; border-left: 4px solid #ffc107; margin: 15px 0; }
          /* Inline markdown styles */
          h1, h2, h3, h4, h5, h6 { color: #2c3e50; margin-top: 1em; margin-bottom: 0.5em; }
          ul, ol { margin: 0 0 1em 1.5em; }
          li { margin-bottom: 0.5em; }
          strong { color: #222; }
          em { color: #555; }
          a { color: #3498db; text-decoration: underline; }
          blockquote { border-left: 4px solid #3498db; margin: 1em 0; padding: 0.5em 1em; color: #555; background: #f8f9fa; }
          code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; font-size: 90%; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🧬 Synthetic Biology Daily Digest</h1>
          <p>Your daily summary of the latest developments in synthetic biology</p>
          <p><strong>${summary.date}</strong></p>
        </div>
        <div class="content">
          <p>Hello ${recipientName},</p>
          <div class="section">
            <h2>📊 Daily Overview</h2>
            <div class="highlight">
              ${dailySummaryHtml}
            </div>
          </div>
          <div class="section">
            <h2>🏆 Top 10 Articles Summary</h2>
            <div class="highlight">
              ${top10SummaryHtml}
            </div>
          </div>
          <div class="section">
            <h2>🎯 Why This Matters</h2>
            <p>Synthetic biology is revolutionizing how we understand and manipulate living systems. Today's discoveries bring us closer to solving some of humanity's biggest challenges, from sustainable energy to medical breakthroughs.</p>
            <p>As a student interested in biology, these developments show you the exciting future of science and the incredible potential of genetic engineering.</p>
          </div>
        </div>
        <div class="footer">
          <p>This digest is automatically generated by AgentBioSummary</p>
          <p>Designed for high school students with an interest in synthetic biology</p>
          <p>To unsubscribe or change settings, please contact your administrator</p>
        </div>
      </body>
      </html>
    `
  }

  private generateEmailText(summary: DailySummary, recipientName: string): string {
    return `
Synthetic Biology Daily Digest - ${summary.date}

Hello ${recipientName},

DAILY OVERVIEW:
${summary.dailySummary}

TOP 10 ARTICLES SUMMARY:
${summary.top10Summary}



WHY THIS MATTERS:
Synthetic biology is revolutionizing how we understand and manipulate living systems. Today's discoveries bring us closer to solving some of humanity's biggest challenges, from sustainable energy to medical breakthroughs.

As a student interested in biology, these developments show you the exciting future of science and the incredible potential of genetic engineering.

---
This digest is automatically generated by AgentBioSummary
Designed for high school students with an interest in synthetic biology
    `
  }

  async sendTestEmail(recipients: EmailRecipient[]): Promise<boolean> {
    try {
      const emailPromises = recipients
        .filter(recipient => recipient.active || recipient.is_active)
        .map(recipient => this.sendBasicTestEmail(recipient))

      const results = await Promise.allSettled(emailPromises)
      const successCount = results.filter(result => result.status === 'fulfilled').length

      console.log(`Test email sent successfully to ${successCount}/${recipients.length} recipients`)
      return successCount > 0
    } catch (error) {
      console.error('Error sending test emails:', error)
      return false
    }
  }

  private async sendBasicTestEmail(recipient: EmailRecipient): Promise<void> {
    const emailHtml = this.generateBasicTestEmailHTML(recipient.name)
    const emailText = this.generateBasicTestEmailText(recipient.name)

    console.log('Attempting to send email to:', recipient.email)
    console.log('Using Resend API key:', process.env.RESEND_API_KEY ? 'Present' : 'Missing')

    try {
      const result = await this.resend.emails.send({
        from: 'noreply@news.ashtekar.net',
        to: recipient.email,
        subject: 'AgentBioSummary - Test Email',
        html: emailHtml,
        text: emailText
      })
      
      console.log('Resend API response:', result)
    } catch (error) {
      console.error('Resend API error:', error)
      throw error
    }
  }

  private generateBasicTestEmailHTML(recipientName: string): string {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AgentBioSummary Test Email</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; }
          .content { background: white; padding: 30px; border-radius: 10px; margin-top: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .success { background: #d4edda; color: #155724; padding: 15px; border-radius: 5px; border-left: 4px solid #28a745; margin: 15px 0; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🧬 AgentBioSummary</h1>
          <p>Test Email - Email System Verification</p>
        </div>
        
        <div class="content">
          <p>Hello ${recipientName},</p>
          
          <div class="success">
            <h2>✅ Email System Test Successful!</h2>
            <p>This is a test email to verify that the AgentBioSummary email system is working correctly.</p>
          </div>
          
          <p>If you received this email, it means:</p>
          <ul>
            <li>✅ The Resend email service is properly configured</li>
            <li>✅ Your email address is correctly set up in the system</li>
            <li>✅ The email templates are working</li>
            <li>✅ Daily summaries will be delivered successfully</li>
          </ul>
          
          <p><strong>What's Next?</strong></p>
          <p>The system will now automatically send you daily synthetic biology summaries at the scheduled time. You can manage your preferences in the AgentBioSummary dashboard.</p>
        </div>
        
        <div class="footer">
          <p>This is a test email from AgentBioSummary</p>
          <p>Designed for high school students with an interest in synthetic biology</p>
        </div>
      </body>
      </html>
    `
  }

  private generateBasicTestEmailText(recipientName: string): string {
    return `
AgentBioSummary - Test Email

Hello ${recipientName},

✅ EMAIL SYSTEM TEST SUCCESSFUL!

This is a test email to verify that the AgentBioSummary email system is working correctly.

If you received this email, it means:
✅ The Resend email service is properly configured
✅ Your email address is correctly set up in the system
✅ The email templates are working
✅ Daily summaries will be delivered successfully

What's Next?
The system will now automatically send you daily synthetic biology summaries at the scheduled time. You can manage your preferences in the AgentBioSummary dashboard.

---
This is a test email from AgentBioSummary
Designed for high school students with an interest in synthetic biology
    `
  }

  async sendErrorNotification(recipients: EmailRecipient[], error: string): Promise<void> {
    try {
      const errorEmailPromises = recipients
        .filter(recipient => recipient.active || recipient.is_active)
        .map(recipient => this.resend.emails.send({
          from: 'AgentBioSummary <noreply@news.ashtekar.net>',
          to: recipient.email,
          subject: 'AgentBioSummary - System Error',
          html: `
            <h2>System Error Notification</h2>
            <p>The AgentBioSummary system encountered an error:</p>
            <pre>${error}</pre>
            <p>Please check the system logs for more details.</p>
          `
        }))

      await Promise.allSettled(errorEmailPromises)
    } catch (error) {
      console.error('Error sending error notification:', error)
    }
  }
}
